language: node_js

node_js:
  - 10

install:
  - npm install -g sass-lint
  - git clone https://github.com/silverstripe/webpack-config.git
  - (cd webpack-config && yarn link)
  - git clone https://github.com/silverstripe/silverstripe-admin.git
  - (cd silverstripe-admin && yarn install && yarn link @silverstripe/webpack-config)
  - (cd silverstripe-admin && yarn add extract-text-webpack-plugin@^2)

script:
  - (cd silverstripe-admin && yarn build)